local launch_json = require("aspire.launch_json")

local fixtures_dir = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":h") .. "/fixtures"

describe("launch_json.strip", function()
  it("removes // line comments outside strings", function()
    local out = launch_json.strip('{\n  // comment\n  "a": 1\n}')
    assert.is_nil(out:find("comment", 1, true))
    assert.is_not_nil(out:find('"a": 1', 1, true))
  end)

  it("removes /* */ block comments outside strings", function()
    local out = launch_json.strip('{\n  /* block\n  comment */\n  "a": 1\n}')
    assert.is_nil(out:find("block", 1, true))
    assert.is_not_nil(out:find('"a": 1', 1, true))
  end)

  it("does not strip // inside a string value", function()
    local out = launch_json.strip('{ "url": "https://aspire.dev/docs" }')
    assert.is_not_nil(out:find("https://aspire.dev/docs", 1, true))
  end)

  it("strips trailing commas before } and ]", function()
    local out = launch_json.strip('{ "a": [1, 2,], "b": 3, }')
    local ok, decoded = pcall(vim.json.decode, out)
    assert.is_true(ok)
    assert.same({ 1, 2 }, decoded.a)
    assert.equals(3, decoded.b)
  end)

  it("does not strip a comma inside a string that looks trailing", function()
    local out = launch_json.strip('{ "note": "a, b," }')
    local ok, decoded = pcall(vim.json.decode, out)
    assert.is_true(ok)
    assert.equals("a, b,", decoded.note)
  end)
end)

describe("launch_json.parse", function()
  it("parses a valid launch.json with comments and trailing commas", function()
    local decoded, err = launch_json.parse(fixtures_dir .. "/valid.jsonc")
    assert.is_nil(err)
    assert.equals(2, #decoded.configurations)
  end)

  it("preserves urls inside strings when comments are present elsewhere", function()
    local decoded, err = launch_json.parse(fixtures_dir .. "/comment_like_string.jsonc")
    assert.is_nil(err)
    local cfg = decoded.configurations[1]
    assert.equals("see https://aspire.dev/docs for details", cfg.note)
  end)

  it("returns an error for an unreadable file", function()
    local decoded, err = launch_json.parse(fixtures_dir .. "/does_not_exist.jsonc")
    assert.is_nil(decoded)
    assert.is_not_nil(err)
  end)
end)

describe("launch_json.find_aspire_config", function()
  it("returns the single aspire config when unambiguous", function()
    local decoded = launch_json.parse(fixtures_dir .. "/valid.jsonc")
    local cfg, matches = launch_json.find_aspire_config(decoded)
    assert.is_nil(matches)
    assert.equals("Aspire: Launch AppHost", cfg.name)
  end)

  it("returns nil, nil when no aspire config exists", function()
    local decoded = launch_json.parse(fixtures_dir .. "/no_aspire.jsonc")
    local cfg, matches = launch_json.find_aspire_config(decoded)
    assert.is_nil(cfg)
    assert.is_nil(matches)
  end)

  it("returns nil, matches when ambiguous and no name given", function()
    local decoded = launch_json.parse(fixtures_dir .. "/multiple_aspire.jsonc")
    local cfg, matches = launch_json.find_aspire_config(decoded)
    assert.is_nil(cfg)
    assert.equals(2, #matches)
  end)

  it("resolves ambiguity via opts.name", function()
    local decoded = launch_json.parse(fixtures_dir .. "/multiple_aspire.jsonc")
    local cfg, matches = launch_json.find_aspire_config(decoded, { name = "Aspire: Launch AppHost B" })
    assert.is_nil(matches)
    assert.equals("Aspire: Launch AppHost B", cfg.name)
  end)

  it("returns nil, nil when opts.name does not match any config", function()
    local decoded = launch_json.parse(fixtures_dir .. "/multiple_aspire.jsonc")
    local cfg, matches = launch_json.find_aspire_config(decoded, { name = "does not exist" })
    assert.is_nil(cfg)
    assert.is_nil(matches)
  end)
end)
